### ISSUE TITLE
A small list of things I've reported on Discord that you may have missed as I didn't ping you

### ISSUE THREAD

**Issue by duskyBabz** [foreverphoenix/the-phoenix-flavour#156]
With all the talk on the Discord server and people reporting things in multiple channels I'm sure it can be easy to miss things on occasion. I try to avoid pinging people and as a result I'm not always sure if you saw what I reported or not so I figured I'd make a small list here.

- ~~it's missing the word "Removed" before "Ghosu’s Auriel’s Quiver Retexture" in the Unique Artifacts part of the changelog~~
   Edit: just saw you fixed that
- Better Volkihar Secret Entrance and Upgraded Moondial (Architecture category) seem to be missing from the changelog
- The models from JS Circlet Replacer do not work on female elves as the guide [doesn't include the JS Circlet Replacer USSEP Fix](https://discord.com/channels/458216677792808961/490889832227143692/817160783858237492). Now admittedly I haven't verified this in-game yet, but since it isn't addressed in the CRP either I am 99% sure this issue is present in TPF 4.0 (in the past the guide [had a patch for CCOR](https://discord.com/channels/458216677792808961/490889832227143692/706984681090056287) that fixed this).

Now [this next thing](https://discord.com/channels/458216677792808961/815224521388851220/817374989036552223) isn't an issue or report (or even something you'd want to include in the guide), but something you may personally be interested in to make creating new saves faster and more convenient for testing purposes now that ASLAL is out, without relying on coc riverwood which is less than ideal for any extensive testing.

Now regarding the facegen part, I see that there are [several plugins](https://user-images.githubusercontent.com/25546565/110137008-a59afe80-7dd0-11eb-85e4-b6a8f225c0d5.png) that add NPCs that you are not checking in zedit before running the script, which I imagine isn't your intention. These plugins are all from the 'Worldspace Additions' and 'Cities & Towns' categories. You can see these specific plugins in the image above but just for clarity's sake, those are:

- UniqueBorderGates-All.esp
- SolstheimLighthouse.esp
- SkaalFishingCamp.esp
- JKs LITE - Cities.esp
- Dragon Bridge.esp
- Rorikstead.esp
- Kynesgrove.esp
- Darkwater Crossing.esp
- Shor's Stone.esp

(Disregard that my NPCsWithFaces plugin has AI Overhaul as master, I have my own setup for character appearance that includes some small tweaks to a few dozen NPCs through plugins, but when it comes to what plugins actually _add_ NPCs it's the same as TPF)

That's it for now, if I spot anything else I'll be sure to report it here as well!

**Comment by foreverphoenix** [comment]
You're a literal angel, thanks a lot for taking the time to open a report on Github. I have like 7 notifications from Carl bot in Discord right now to remind me of various things to check and potentially fix when I have the time. It's ever so slightly stressful.

- Missing more stuff on the changelog. Will fix this soon.
- Missing JS Circlets patch. Yup didn't think of adding the USSEP one after removing the CCOR one. Fixing soon.
- Had a look at your alt start suggestion and I'm liking it. Will try it out!

As for the NPCs, that's a bit embarrassing. I knew JK's added some NPCs to Windhelm but since I was gonna remove the mod anyway, I ignored them. The other mods I straight up didn't check. Thankfully the majority will get the boot soon enough. The others I will add to the instructions.

Thanks again!

**Comment by foreverphoenix** [comment]
All done in 4.4.3
